#!/bin/sh

# This is a simple script for running the BioLegato bltable application
# for demonstration purposes. In a full BIRCH system, there are more
# versatile ways of setting environment variables and such.

#------------------------ BIRCH and BIRCH_PLATFORM ---------------
#
#  Set these two variables and everything else should work unchanged.
#
# In a full BIRCH system, these variables are set by getbirch as
# part of an install or update.

# Set BIRCH environment variable, on which everything else depends
BIRCH=/home/psgendb/BIRCHDEV/java/bioLegato/test
export BIRCH

# Uncomment one choice for BIRCH_PLATFORM
BIRCH_PLATFORM="linux-x86_64"
#BIRCH_PLATFORM="osx-x86_64"
export BIRCH_PLATFORM
#-----------------------------------------------------------------


#Path should include the script directory
PATH=$BIRCH/script:$BIRCH/bin-$BIRCH_PLATFORM:$PATH
export PATH

# Set environment variables for helper applications
. $BIRCH/admin/setblenv.profile.$BIRCH_PLATFORM.source

# Location of BioLegato .jar files
BIOLEGATO_HOME=$BIRCH/java/bioLegato
export BIOLEGATO_HOME

BL_PROPERTIES=$BIRCH/dat/bltable/bltable.properties
export BL_PROPERTIES

# We need to explicitly set the default look and feel. On Mac OSX, the default for the 
# table canvas has no borders around cells, which detracts from readability.
java -Dswing.defaultlaf=javax.swing.plaf.metal.MetalLookAndFeel -jar $BIOLEGATO_HOME/table.jar $*


