/* Generated By:JavaCC: Do not edit this line. PCDTreeConstants.java Version 5.0 */
package org.biopcd.parser;

public interface PCDTreeConstants
{
  public int JJTPARSEFULLMENU = 0;
  public int JJTPARSEMENUITEM = 1;
  public int JJTBODY = 2;
  public int JJTCONTENT = 3;
  public int JJTTAB = 4;
  public int JJTPANEL = 5;
  public int JJTACT = 6;
  public int JJTPARAM = 7;
  public int JJTBUTTONFIELDS = 8;
  public int JJTLISTFIELDS = 9;
  public int JJTTEXTFIELDS = 10;
  public int JJTTEXTAREAFIELDS = 11;
  public int JJTNUMBERFIELDS = 12;
  public int JJTDECIMALFIELDS = 13;
  public int JJTFILEFIELDS = 14;
  public int JJTDIRFIELDS = 15;
  public int JJTTEMPFILEFIELDS = 16;
  public int JJTFILEFORMAT = 17;
  public int JJTSYSTEMNAME = 18;
  public int JJTARCHLIST = 19;
  public int JJTARCHNAME = 20;
  public int JJTPARSEDBCONNECT = 21;
  public int JJTFULLSQLQUERY = 22;
  public int JJTIDENT = 23;
  public int JJTTEXT = 24;
  public int JJTDECIMAL = 25;
  public int JJTNUMBER = 26;
  public int JJTBOOL = 27;
  public int JJTASSERTINDENT = 28;
  public int JJTTESTINDENT = 29;
  public int JJTNL = 30;


  public String[] jjtNodeName = {
    "parseFullMenu",
    "parseMenuItem",
    "Body",
    "Content",
    "Tab",
    "Panel",
    "Act",
    "Param",
    "buttonFields",
    "listFields",
    "textFields",
    "textAreaFields",
    "numberFields",
    "decimalFields",
    "fileFields",
    "dirFields",
    "tempfileFields",
    "FileFormat",
    "SystemName",
    "ArchList",
    "ArchName",
    "ParseDBConnect",
    "FullSQLQuery",
    "Ident",
    "Text",
    "Decimal",
    "Number",
    "Bool",
    "assertIndent",
    "testIndent",
    "nl",
  };
}
/* JavaCC - OriginalChecksum=1698052b579a5f2778a223c994941e40 (do not edit this line) */
